language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

env:
  global:
    - SYMFONY_ENV=test

before_script:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit

matrix:
  allow_failures:
    - php: hhvm-nightly # hhvm-nightly currently chokes on composer installation